Fix missing include directory for LiteCore/Support
Fixes the following error:

In file included from /path/to/couchbase-lite-C/src/CBLBase.cc:21:
/path/to/couchbase-lite-C/src/Listener.hh:22:10: fatal error:
      'access_lock.hh' file not found
         ^~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/CouchbaseLiteCStatic.dir/src/CBLBase.cc.o] Error 1
make[1]: *** [CMakeFiles/CouchbaseLiteCStatic.dir/all] Error 2

The CMake include paths now match the XCode ones.