Fix C++23 build errors due to std::make_unique on forward declared class
When C++23 is enabled (CMAKE_CXX_STANDARD=23) there are errors such as:

  error: allocation of incomplete type 'cbl::CollectionChange'

The problem appears to be related to std::make_unique becoming constexpr in C++23; this change fixes the build for C++23 by ensuring std::make_unique is called after the types are fully defined.